name: Deploy Docker Container

on:
  push:
    branches:
      - Production
      - Dev
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up SSH for deployment
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy to the server
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 2222
          script: |
            echo "Deploying branch $GITHUB_REF"

            # Navigate to the correct directory where the project is located
            cd /home/${{ secrets.SSH_USER }}/genesis-backend || exit 1

            # Extract the branch name and convert to lowercase
            BRANCH_NAME="${GITHUB_REF}"
            CONTAINER_NAME=$(echo $BRANCH_NAME | sed 's/refs\/heads\///' | tr '[:upper:]' '[:lower:]')

            # Set the port based on the branch
            case "$CONTAINER_NAME" in
              "production")
                OUTGOING_PORT=8088
                ;;
              "dev")
                OUTGOING_PORT=8089
                ;;
              "qa")
                OUTGOING_PORT=8090
                ;;
              *)
                echo "Unknown branch, setting default port 8080"
                OUTGOING_PORT=8080
                ;;
            esac
            echo "Using port: $OUTGOING_PORT"

            # Stop and remove old container
            echo "Stopping and removing container: cmb-$CONTAINER_NAME"
            docker stop cmb-$CONTAINER_NAME || true
            docker rm cmb-$CONTAINER_NAME || true

            # Copy the built image from the CI runner to the server
            docker save cmb-$CONTAINER_NAME:latest | bzip2 | sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@$SERVER_IP 'docker load < bzcat > /tmp/cmb-$CONTAINER_NAME.tar.bz2'

            # Run the new container with the correct port and restart policy
            echo "Running new container: cmb-$CONTAINER_NAME"
            docker run -d --name cmb-$CONTAINER_NAME \
              --restart always \
              -p $OUTGOING_PORT:$OUTGOING_PORT \
              cmb-$CONTAINER_NAME:latest

        env:
          OUTGOING_PORT: 8088
