name: Deploy Project

on:
  push:
    branches:
      - Production
      - Dev
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH for deployment
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: "81.10.229.31"
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 2222
        script: |
          SERVER_IP="81.10.229.31"
          echo "Deploying branch $GITHUB_REF"
          
          # Hardcode branch name as 'Dev' for testing
          BRANCH_NAME="Dev"  
          echo "Hardcoded Branch Name: $BRANCH_NAME"  # Debugging output

          # Ensure the branch name is not empty
          if [ -z "$BRANCH_NAME" ]; then
            echo "ERROR: Branch name extraction failed"
            exit 1
          fi

          CONTAINER_NAME=$(echo $BRANCH_NAME | tr '[:upper:]' '[:lower:]')  # Convert branch name to lowercase for the container name
          echo "Container Name: $CONTAINER_NAME"  # Debugging output

          # Set the port based on the branch
          case "$CONTAINER_NAME" in
            "production")
              OUTGOING_PORT=8088
              ;;
            "dev")
              OUTGOING_PORT=8086
              ;;
            "qa")
              OUTGOING_PORT=8087
              ;;
            *)
              echo "Unknown branch, setting default port 8079"
              OUTGOING_PORT=8079
              ;;
          esac
          echo "Using port: $OUTGOING_PORT"

          # Navigate to the project directory
          cd /home/***/genesis-backend || exit 1

          # Check if the container already exists
          if [[ $(docker ps -a --filter "name=cmb-$CONTAINER_NAME" -q) ]]; then
            echo "Container cmb-$CONTAINER_NAME already exists. Skipping removal."
          else
            # If the container does not exist, build the image
            echo "Container cmb-$CONTAINER_NAME does not exist. Building image."
            docker build -t cmb-$CONTAINER_NAME .
          fi

          # Stop and remove the old container if it exists
          echo "Stopping and removing container: cmb-$CONTAINER_NAME"
          docker stop cmb-$CONTAINER_NAME || true
          docker rm cmb-$CONTAINER_NAME || true

          # Copy the built image from the CI runner to the server
          echo "Loading image into Docker"
          docker save cmb-$CONTAINER_NAME:latest | bzip2 | sshpass -p "***" ssh -o StrictHostKeyChecking=no -p 2222 ***@$SERVER_IP 'bzcat | docker load'

          # Run the new container with the correct port and restart policy
          echo "Running new container: cmb-$CONTAINER_NAME"
          docker run -d --name cmb-$CONTAINER_NAME \
            --restart always \
            -p $OUTGOING_PORT:8088 \
            cmb-$CONTAINER_NAME:latest

