name: Docker Image CI

on:
  push:
    branches: [ "Production", "Dev", "QA" ]
  pull_request:
    branches: [ "Production", "Dev", "QA" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag genesis-backend:$(date +%s)
