name: Merge Dev into Production

on:
  schedule:
    - cron: '0 4 * * 1' # Runs every Monday at 4:00 UTC (6:00 CEST)
  workflow_dispatch: # Allows manual trigger

jobs:
  merge_dev_to_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout Production branch
        run: |
          git checkout Production
          git pull origin Production

      - name: Merge Dev into Production
        run: |
          git merge origin/Dev --allow-unrelated-histories --no-edit

      - name: Push changes to Production
        run: git push origin Production
